development:
  adapter: postgresql
  encoding: utf8
  database: hv_development
  pool: 5
  username: huntuse
  password: huntpass

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: hv_test
  pool: 5
  username: huntuse
  password: huntpass
